# Generated by Django 2.1.7 on 2019-02-20 13:17

from django.db import migrations
from django.contrib.auth import get_user_model

User = get_user_model()


def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'admin'
    superuser.email = 'admin@admin.net'
    superuser.set_password('admin')
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
